server:
  port: 8083

spring:
  application:
    name: receiver

  # Kafka Configuration - Consumer./mvnw
  kafka:
    bootstrap-servers: ec2-13-204-84-61.ap-south-1.compute.amazonaws.com:8080
    consumer:
      group-id: receiver-group-one
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties.spring.json.trusted-packages: "*"
      enable-auto-commit: false

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/